# Generated by Django 5.0.6 on 2024-06-21 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeterType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Remote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('chip_select', models.IntegerField(unique=True, verbose_name='Chip Select Pin on Pi')),
                ('inputs', models.IntegerField(default=8, verbose_name='Number of Inputs on Remote')),
                ('vdd', models.FloatField(default=5.0, verbose_name='VDD for remote')),
                ('max_value', models.IntegerField(default=1024, verbose_name='Maximum raw value')),
            ],
        ),
        migrations.CreateModel(
            name='SerialBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('sck', models.IntegerField(unique=True, verbose_name='SPI Clock Pin')),
                ('mosi', models.IntegerField(unique=True, verbose_name='Master Out, Slave In')),
                ('miso', models.IntegerField(unique=True, verbose_name='Master In, Slave Out')),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('input_number', models.IntegerField()),
                ('calibrated_zero', models.IntegerField(default=512)),
                ('ratio', models.FloatField(default=20)),
                ('associated_voltage_meter', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='power_meters.meter')),
                ('meter_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='power_meters.metertype')),
                ('remote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='power_meters.remote')),
            ],
        ),
        migrations.CreateModel(
            name='HourlyMeasurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rms', models.FloatField(verbose_name='Average RMS Value')),
                ('whr', models.FloatField(verbose_name='Watt Hour')),
                ('peak_rms', models.FloatField(verbose_name='Highest RMS Value')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='power_meters.meter')),
            ],
        ),
        migrations.CreateModel(
            name='DailyMeasurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rms', models.FloatField(verbose_name='Average RMS Value')),
                ('whr', models.FloatField(verbose_name='Watt Hour')),
                ('peak_hr', models.IntegerField(verbose_name='Peak Demand Hour')),
                ('peak_hr_usage', models.FloatField(verbose_name='Wh Usage at Peak Hour')),
                ('peak_rms', models.FloatField(verbose_name='Highest RMS Value')),
                ('peak_demand_period', models.IntegerField(verbose_name='Peak Demand Period')),
                ('peak_demand_usage', models.FloatField(verbose_name='Wh Usage at Peak Period')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='power_meters.meter')),
            ],
        ),
        migrations.CreateModel(
            name='MinuteMeasurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rms', models.FloatField(verbose_name='Average RMS Value')),
                ('whr', models.FloatField(verbose_name='Watt Hour')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='power_meters.meter')),
            ],
        ),
        migrations.CreateModel(
            name='SecondMeasurements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rms', models.FloatField(verbose_name='RMS Value')),
                ('whr', models.FloatField(verbose_name='Watt Hour')),
                ('raw_peak', models.IntegerField(verbose_name='Highest Raw Value')),
                ('raw_min', models.IntegerField(verbose_name='Lowest Raw Value')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='power_meters.meter')),
            ],
        ),
        migrations.AddField(
            model_name='remote',
            name='serial_bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='power_meters.serialbus'),
        ),
    ]
