# Generated by Django 5.0.6 on 2024-06-20 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('power_meters', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MeterTypes',
            new_name='MeterType',
        ),
    ]
