# Generated by Django 5.0.6 on 2024-06-20 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('power_meters', '0002_rename_metertypes_metertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meter',
            name='associated_voltage_meter',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='power_meters.meter'),
        ),
    ]
